# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Scarf" do
pod 'RestKit', '~> 0.22.0'
pod 'ReactiveCocoa', '~> 2.1.8'
end

target "ScarfTests" do

end

